services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      fibertime-net:
        aliases:
          - nginx

  fibertime-fe:
    build:
      context: ./fibertime_fe
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./fibertime_fe:/app:ro
      - ./fibertime_fe/package-lock.json:/app/package-lock.json
      - fe-next:/app/.next
      - fe-modules:/app/node_modules
    networks:
      fibertime-net:
        aliases:
          - fibertime-fe
    depends_on:
      - nginx
    restart: always

  fibertime-be:
    build:
      context: ./fibertime_be
      dockerfile: ./Dockerfile.dev
    command: sh -c "node dist/seed.js && node dist/main.js"
    volumes:
      - ./fibertime_be:/app
      - be-modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      fibertime-net:
        aliases:
          - fibertime-be
    environment:
      - MONGO_URI=mongodb://fibertime_mongo:27017/fibertime
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - JWT_SECRET=superman
      - JWT_EXPIRES_IN=15m
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:6
    container_name: fibertime_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      fibertime-net:
        aliases:
          - mongo

  redis:
    image: redis:7-alpine
    container_name: fibertime_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      fibertime-net:
        aliases:
          - redis
    restart: always

networks:
  fibertime-net:

volumes:
  fe-modules:
  fe-next:
  be-modules:
  redis_data:
  mongo_data: